define([], function () {
  return {
    "ProjectEndpointFieldLabel": "Project Endpoint",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "Cmessage": "this is my custom message",
    'DocumentProjectSpecificFieldsHeader': 'Project-Specific Fields Configuration',
    'PorjectAttributesHeader': 'Project Metadata',
    'AdminPageTitle': 'Project Configuration',
    'ProjectTemplatesHeader':'Templates',
    'ErrorLoadingProjectConfig':'An error occurred while loading the project configuration. Please try again later.',
    'EndCustomerField': 'End Customer',
    'ProductLineField': 'Product Line',
    'LanguageField': 'Language',
    'ModificationDateField': 'Modification Date',
    'CreatorField': 'Created By',
    'ProjectNameField': 'Project Name',
    'DirectCustomerField': 'Direct Customer',
    'PLOwnerShipFieldPanelTitle': 'Select PL Ownership',
    'PLOwnerShipField': 'Project PL Ownership',
    'IsActiveProjectField': 'Is Active',
    'MigratedProjectField': 'Is Migrated',
    'EditorField': 'Last Modified By',
    'GeographyField': 'Geography',
    'CreationDateField': 'Creation Date',
    'ProjectTypeField': 'Project Type',
    'ContractCodeField': 'Contract Code',
    'ValidationErrorRequiredValueMissing': 'This field is required',
    'ProductField': 'Product',
    'ProductPanelTitle': 'Select Product',
    'ProjectAliasField': 'Alias',
    'Save': 'Save',
    'Cancel': 'Cancel',
    'ErrorSavingProjectConfig': 'An error occurred while saving the project configuration. Please try again later.',
    'ErrorCaseBadRequest':'Bad request, please check the input values.',
    'ErrorCaseNotFound':'Not Found, the requested resource could not be found.',
    'ErrorCaseBadGateway':'Bad Gateway, there was an issue with the server.',
    'ErrorCaseServiceunavaliable':'Service Unavailable, the service is temporarily unavailable. Please try again later.',
    'projectConfigurationPageURL': 'Project configuration page url',
    'TemplateDialogTitle':'Content types',
    'ErrorDialogTitle':'Error',
    'ErrorMsg':'❌ An error occurred while processing your request.Please try again later.',
    'CreatedDialogTitle': 'Created success',
    'SuccessMessage': '✅ Content type created successfully.',
    'UpdatedDialogTitle': 'Updated success',
    'UpdatedMessage': '✅ Content type updated successfully.',
    'DeletedDialogTitle': 'Deleted success',
    'DeletedMessage': '✅ Content type deleted successfully.',
    'ErrorMessage': "Error reading file",

  }
});