define([], function() {
  return {
    "Save": "Save",
    "Cancel": "Cancel",
    "Close": "Close",
    'UncategorisedFieldsSection': 'Other',
    'NewFormHeader': 'New',
    'EditFormHeader': 'Edit',
    'ViewFormHeader': 'View',
    'OnlyDocumentControllerCanCreateDocument': 'You must have the Document Controller role to create a document.',
    'ErrorLoadingForm': 'Sorry, there was an error loading the form. Please try again later.',
    'ValidationError': 'Please correct the highlighted fields/sections before saving the form.',
    'EditButtonText': 'Edit',
    'validationErrorRequiredMissingValue':'This field is required',
    'URLFieldUrl': 'URL',
    'URLFieldDescription': 'Label',
    'validationErrorInvalidUrlFormat': 'Invalid URL format',
    'taxPickerPanelTitle': 'Select a term',
    'errorLoadingField': 'An error occurred while loading the field. Please try again later.',
    'validationErrorInvalidFormat': 'This field has invalid values.',
    'onErrorDuringValidation': 'An error occurred during validation. Please try again later.',
    'SaveError': 'An error occurred while saving the form. Please try again later.',
    'PartialSaveError': 'The form could not be saved. Please correct the highlighted fields/sections, or try again later.',
    'FieldLoadError': 'An error occurred while loading the following field(s): "{0}". Please try again later.',
    'AddError': 'An error occurred while adding the item. Please try again later.',
    'CleanError': 'Could not cleanup errored item. Please check the draft library for a corrupted item.',
    'validationErrorProjectReferenceMissing': 'This document has no project reference. Please set a revision after a project reference is set.',
    'validationErrorSpecialCharacters':'Special characters are not allowed in the Revision field.Please set a new Revision.',
    'ValidationErrorSpecialCharctersInReference':'Special characters are not allowed in the Reference field.Please set a new Reference.',
    'validationErrorDuplicateRevision': 'This document already has a revision with the same number. Please set a unique revision number.',
    'ConfidentialityLevelPreSaveOperationLabel': 'Setting access permissions according to sensitivity level...',
    'ConfidentialityLevelUsers':'Users',
    'RunninPresaveOperations': 'Running pre-save operations...',
    'OffText': 'No',
    'OnText': 'Yes'
  }
});